package persistencias;
// Generated 13 feb 2025, 10:17:18 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import  static javax.persistence.GenerationType.IDENTITY;
/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name="equipo" , catalog="liga_fantasy")
public class Equipo implements java.io.Serializable {

	private int idEquipo;
	private String nombre;
	private int victorias;
	private int empates;
	private int derrotas;
	private int puntos;
	private int golesFavor;
	private int golesContra; 
	private boolean equipoJugador;
	private Set<Partido>  partidosForIdEquipoVisitante = new HashSet(0);
	private Set<Partido>  partidosForIdEquipoLocal = new HashSet(0);
	private Set<Jugador> jugadors = new HashSet(0);

	public Equipo() {
	}

	public Equipo(int idEquipo, String nombre, int victorias, int empates, int derrotas, int puntos,
			boolean equipoJugador) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.victorias = victorias;
		this.empates = empates;
		this.derrotas = derrotas;
		this.puntos = puntos;
		this.equipoJugador = equipoJugador;
	}

	public Equipo(int idEquipo, String nombre, int victorias, int empates, int derrotas, int puntos,
			boolean equipoJugador, Set partidosForIdEquipoVisitante, Set partidosForIdEquipoLocal, Set jugadors) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.victorias = victorias;
		this.empates = empates;
		this.derrotas = derrotas;
		this.puntos = puntos;
		this.equipoJugador = equipoJugador;
		this.partidosForIdEquipoVisitante = partidosForIdEquipoVisitante;
		this.partidosForIdEquipoLocal = partidosForIdEquipoLocal;
		this.jugadors = jugadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name="id_equipo", unique = true, nullable = false)
	public int getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(int idEquipo) {
		this.idEquipo = idEquipo;
	}
	
	@Column(name="nombre",nullable=false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@Column(name="victorias",nullable=true)
	public int getVictorias() {
		return this.victorias;
	}

	public void setVictorias(int victorias) {
		this.victorias = victorias;
	}
	@Column(name="empates",nullable=true)
	public int getEmpates() {
		return this.empates;
	}

	public void setEmpates(int empates) {
		this.empates = empates;
	}
	@Column(name="derrotas",nullable=true)
	public int getDerrotas() {
		return this.derrotas;
	}

	public void setDerrotas(int derrotas) {
		this.derrotas = derrotas;
	}
	@Column(name="puntos",nullable=true)
	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}
	@Column(name="equipo_jugador",nullable=true)
	public boolean isEquipoJugador() {
		return this.equipoJugador;
	}

	public void setEquipoJugador(boolean equipoJugador) {
		this.equipoJugador = equipoJugador;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "equipoByIdEquipoVisitante")
	public Set<Partido> getPartidosForIdEquipoVisitante() {
		return this.partidosForIdEquipoVisitante;
	}

	public void setPartidosForIdEquipoVisitante(Set<Partido>  partidosForIdEquipoVisitante) {
		this.partidosForIdEquipoVisitante = partidosForIdEquipoVisitante;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "equipoByIdEquipoLocal")
	public Set<Partido> getPartidosForIdEquipoLocal() {
		return this.partidosForIdEquipoLocal;
	}

	public void setPartidosForIdEquipoLocal(Set<Partido>  partidosForIdEquipoLocal) {
		this.partidosForIdEquipoLocal = partidosForIdEquipoLocal;
	}
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "equipo")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}
	@Column(name="goles_favor", nullable=false)
	public int getGolesFavor() {
		return golesFavor;
	}

	public void setGolesFavor(int golesFavor) {
		this.golesFavor = golesFavor;
	}
	@Column(name="goles_contra", nullable=false)
	public int getGolesContra() {
		return golesContra;
	}

	public void setGolesContra(int golesContra) {
		this.golesContra = golesContra;
	}
	

}
