package persistencias;
// Generated 13 feb 2025, 10:17:18 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private int idEquipo;
	private String nombre;
	private int victorias;
	private int empates;
	private int derrotas;
	private int puntos;
	private boolean equipoJugador;
	private Set partidosForIdEquipoVisitante = new HashSet(0);
	private Set partidosForIdEquipoLocal = new HashSet(0);
	private Set jugadors = new HashSet(0);

	public Equipo() {
	}

	public Equipo(int idEquipo, String nombre, int victorias, int empates, int derrotas, int puntos,
			boolean equipoJugador) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.victorias = victorias;
		this.empates = empates;
		this.derrotas = derrotas;
		this.puntos = puntos;
		this.equipoJugador = equipoJugador;
	}

	public Equipo(int idEquipo, String nombre, int victorias, int empates, int derrotas, int puntos,
			boolean equipoJugador, Set partidosForIdEquipoVisitante, Set partidosForIdEquipoLocal, Set jugadors) {
		this.idEquipo = idEquipo;
		this.nombre = nombre;
		this.victorias = victorias;
		this.empates = empates;
		this.derrotas = derrotas;
		this.puntos = puntos;
		this.equipoJugador = equipoJugador;
		this.partidosForIdEquipoVisitante = partidosForIdEquipoVisitante;
		this.partidosForIdEquipoLocal = partidosForIdEquipoLocal;
		this.jugadors = jugadors;
	}

	public int getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(int idEquipo) {
		this.idEquipo = idEquipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getVictorias() {
		return this.victorias;
	}

	public void setVictorias(int victorias) {
		this.victorias = victorias;
	}

	public int getEmpates() {
		return this.empates;
	}

	public void setEmpates(int empates) {
		this.empates = empates;
	}

	public int getDerrotas() {
		return this.derrotas;
	}

	public void setDerrotas(int derrotas) {
		this.derrotas = derrotas;
	}

	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}

	public boolean isEquipoJugador() {
		return this.equipoJugador;
	}

	public void setEquipoJugador(boolean equipoJugador) {
		this.equipoJugador = equipoJugador;
	}

	public Set getPartidosForIdEquipoVisitante() {
		return this.partidosForIdEquipoVisitante;
	}

	public void setPartidosForIdEquipoVisitante(Set partidosForIdEquipoVisitante) {
		this.partidosForIdEquipoVisitante = partidosForIdEquipoVisitante;
	}

	public Set getPartidosForIdEquipoLocal() {
		return this.partidosForIdEquipoLocal;
	}

	public void setPartidosForIdEquipoLocal(Set partidosForIdEquipoLocal) {
		this.partidosForIdEquipoLocal = partidosForIdEquipoLocal;
	}

	public Set getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set jugadors) {
		this.jugadors = jugadors;
	}

}
