package persistencias;
// Generated 5 feb 2025, 13:07:02 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private Integer idEquipo;
	private String nombre;
	private int victorias;
	private int empates;
	private int derrotas;
	private int puntos;
	private int portero;
	private int defensa;
	private int centrocampista;
	private int delantero;
	private Set jugadors = new HashSet(0);

	public Equipo() {
	}

	public Equipo(String nombre, int victorias, int empates, int derrotas, int puntos, int portero, int defensa,
			int centrocampista, int delantero) {
		this.nombre = nombre;
		this.victorias = victorias;
		this.empates = empates;
		this.derrotas = derrotas;
		this.puntos = puntos;
		this.portero = portero;
		this.defensa = defensa;
		this.centrocampista = centrocampista;
		this.delantero = delantero;
	}

	public Equipo(String nombre, int victorias, int empates, int derrotas, int puntos, int portero, int defensa,
			int centrocampista, int delantero, Set jugadors) {
		this.nombre = nombre;
		this.victorias = victorias;
		this.empates = empates;
		this.derrotas = derrotas;
		this.puntos = puntos;
		this.portero = portero;
		this.defensa = defensa;
		this.centrocampista = centrocampista;
		this.delantero = delantero;
		this.jugadors = jugadors;
	}

	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getVictorias() {
		return this.victorias;
	}

	public void setVictorias(int victorias) {
		this.victorias = victorias;
	}

	public int getEmpates() {
		return this.empates;
	}

	public void setEmpates(int empates) {
		this.empates = empates;
	}

	public int getDerrotas() {
		return this.derrotas;
	}

	public void setDerrotas(int derrotas) {
		this.derrotas = derrotas;
	}

	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}

	public int getPortero() {
		return this.portero;
	}

	public void setPortero(int portero) {
		this.portero = portero;
	}

	public int getDefensa() {
		return this.defensa;
	}

	public void setDefensa(int defensa) {
		this.defensa = defensa;
	}

	public int getCentrocampista() {
		return this.centrocampista;
	}

	public void setCentrocampista(int centrocampista) {
		this.centrocampista = centrocampista;
	}

	public int getDelantero() {
		return this.delantero;
	}

	public void setDelantero(int delantero) {
		this.delantero = delantero;
	}

	public Set getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set jugadors) {
		this.jugadors = jugadors;
	}

}
