package persistencias;
// Generated 13 feb 2025, 10:17:18 by Hibernate Tools 5.4.33.Final

/**
 * Partido generated by hbm2java
 */
public class Partido implements java.io.Serializable {

	private int idPartido;
	private Equipo equipoByIdEquipoVisitante;
	private Equipo equipoByIdEquipoLocal;
	private int jornada;
	private Integer golesLocal;
	private Integer golesVisitante;

	public Partido() {
	}

	public Partido(int idPartido, int jornada) {
		this.idPartido = idPartido;
		this.jornada = jornada;
	}

	public Partido(int idPartido, Equipo equipoByIdEquipoVisitante, Equipo equipoByIdEquipoLocal, int jornada,
			Integer golesLocal, Integer golesVisitante) {
		this.idPartido = idPartido;
		this.equipoByIdEquipoVisitante = equipoByIdEquipoVisitante;
		this.equipoByIdEquipoLocal = equipoByIdEquipoLocal;
		this.jornada = jornada;
		this.golesLocal = golesLocal;
		this.golesVisitante = golesVisitante;
	}

	public int getIdPartido() {
		return this.idPartido;
	}

	public void setIdPartido(int idPartido) {
		this.idPartido = idPartido;
	}

	public Equipo getEquipoByIdEquipoVisitante() {
		return this.equipoByIdEquipoVisitante;
	}

	public void setEquipoByIdEquipoVisitante(Equipo equipoByIdEquipoVisitante) {
		this.equipoByIdEquipoVisitante = equipoByIdEquipoVisitante;
	}

	public Equipo getEquipoByIdEquipoLocal() {
		return this.equipoByIdEquipoLocal;
	}

	public void setEquipoByIdEquipoLocal(Equipo equipoByIdEquipoLocal) {
		this.equipoByIdEquipoLocal = equipoByIdEquipoLocal;
	}

	public int getJornada() {
		return this.jornada;
	}

	public void setJornada(int jornada) {
		this.jornada = jornada;
	}

	public Integer getGolesLocal() {
		return this.golesLocal;
	}

	public void setGolesLocal(Integer golesLocal) {
		this.golesLocal = golesLocal;
	}

	public Integer getGolesVisitante() {
		return this.golesVisitante;
	}

	public void setGolesVisitante(Integer golesVisitante) {
		this.golesVisitante = golesVisitante;
	}

}
